name: GitHub Web Automation

on: [push]

jobs:
  automate-github-ui:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

        # Get the installed Chrome version
        CHROME_VERSION=$(google-chrome --version | sed -E 's/Google Chrome ([0-9]+\.[0-9]+\.[0-9]+).*/\1/')
        echo "Detected Chrome version: $CHROME_VERSION"

        # Get the corresponding ChromeDriver version
        CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
        echo "Matching ChromeDriver version: $CHROMEDRIVER_VERSION"

        # Download and install ChromeDriver
        curl -L -O "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/bin/chromedriver
        sudo chmod +x /usr/bin/chromedriver
