name: App Workflow

on:
  push:
    branches:
      - main

jobs:
  app-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Install Dependencies
      run: mvn -B install --file pom.xml

    - name: Run Tests
      run: mvn test --file pom.xml
